#!/bin/bash
yum -y clean all
yum -y install mod_ssl
yum -y install crypto-utils
yum -y install git 
yum -y install sudo
yum -y install wget
yum -y install ntpd
yum groupinstall -y 'development tools'
yum -y install zlib-devel bzip2-devel openssl-devel ncurses-devel sqlite-devel readline-devel tk-devel gdbm-devel db4-devel libpcap-devel xz-devel
yum -y install tar
yum -y install epel-release
cd /tmp && wget http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm && rpm -ivh nginx-release-centos-6-0.el6.ngx.noarch.rpm
yum -y install nginx
chkconfig nginx on
rpm -Uvh https://download.newrelic.com/pub/newrelic/el5/x86_64/newrelic-repo-5-3.noarch.rpm
yum -y install newrelic-sysmond
nrsysmond-config --set license_key=
cd /etc/init.d/
wget https://raw.githubusercontent.com/avichalbadaya/cloudformation_example/625390b217d620cfa81b0bd176b9af72f2ca0579/django_app_init
chmod 755 django_app_init
chkconfig django_app_init on
cd /tmp
wget https://raw.githubusercontent.com/avichalbadaya/cloudformation_example/32d2d3a2c95f44f6659250360faca6555b95cc76/default.conf
yes | cp default.conf /etc/nginx/conf.d/
service newrelic-sysmond start
service nginx start
